"""Second  Migration

Revision ID: 35949f76db5e
Revises: 22d3ec834569
Create Date: 2021-12-09 14:59:39.923334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35949f76db5e'
down_revision = '22d3ec834569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
