"""3  Migration

Revision ID: 52cfc46965ff
Revises: c2726e438088
Create Date: 2021-12-09 15:15:03.519842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cfc46965ff'
down_revision = 'c2726e438088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('mode', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'coupons', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='unique')
    op.drop_column('coupons', 'mode')
    # ### end Alembic commands ###
