"""3  Migration

Revision ID: c2726e438088
Revises: 35949f76db5e
Create Date: 2021-12-09 15:11:28.801068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2726e438088'
down_revision = '35949f76db5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'teste')
    op.drop_column('coupons', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('type', sa.VARCHAR(length=15), nullable=True))
    op.add_column('coupons', sa.Column('teste', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
